### ISSUE TITLE
Dependency on GPy and GPyOpt

### ISSUE THREAD

**Issue by apaleyes** [EmuKit/emukit#140]
I'd like to open a discussion on Emukit's dependency on GPy and GPyOpt.

GPy dependency causes us some trouble: it is most likely cause of installation failures, it drags in matplotlib and plotly, and it has [known issues](https://github.com/SheffieldML/GPyOpt/issues/193) with Python 3.7. For these reasons I would like to see if we could somehow get rid of that dependency being required.

We depend on GPy and GPyOpt in following places:
1. Model free designs
It is possible to even copy over relevant code pieces from GPyOpt and get rid of that dependency.
2. Optimizer
Same thing, we could copy, or re-impelement
3. Multi-fidelity
This is harder, but we could consider multi-fidelity as an extra bit of the package. People could successfully run decision loops in Emukit without multi-fidelity feature.

Note that 1 and 2 help us remove GPyOpt as a dependency at all.

Opinions welcome.

**Comment by apaleyes** [comment]
Point 1 above is addressed.

**Comment by marpulli** [comment]
We have removed the GPyOpt dependency. Do we actually want to remove the GPy dependency?

**Comment by apaleyes** [comment]
I actually think we do. GPy only comes into play if users want to use multi-fidelity models, so you don't need GPy for core outer loop stuff of the library. Besides we always talk about how we are model agnostic and how emukit can be used with any modelling backend, and yet we install GPy along with it.

Here is the list of dependencies we get installed on a completely new and clean python environment:

```
Installing collected packages: setuptools, numpy, scipy, six, decorator, paramz, kiwisolver, cycler, pyparsing, python-dateutil, matplotlib, retrying, certifi, idna, urllib3, chardet, requests, attrs, pyrsistent, jsonschema, ipython-genutils, traitlets, jupyter-core, nbformat, pytz, plotly, GPy, emcee, emukit
```

Most of that is dragged along by GPy, and I think that's a lot for a relatively tiny library such as emukit.

**Comment by marpulli** [comment]
As well as the multi-fidelity package, we also need some modelling package to run the intro code. Our model for the intro code doesn't necessarily have to be done with GPy, we could use sklearn if we think that's going to be better maintained in the future. We could even just implement a very simple GP model in emukit examples.

**Comment by apaleyes** [comment]
Oh, having a simple GP implementation for basic stuff is a great idea, let's look into that

**Comment by mmahsereci** [comment]
We also use GPy in the tutorial notebooks and some tests at the moment. @marpulli  What do you mean by "intro code"?

**Comment by marpulli** [comment]
I copied the term from #214 ! I don't really know, but the code in the docs should at least run without GPy if we remove it as a dependency. The "intro" notebooks should also run. 

I'd consider the intro notebooks to be:
- Emukit-tutorial-basic-use-of-the-library
- Emukit-tutorial-intro

and maybe the BayesOpt intro. I think it is fine in general for notebooks to have other dependencies (we have one that depends on tensorflow for instance).

**Comment by mmahsereci** [comment]
I guess for notebooks it makes sense how you say. We might need to rewrite some tests that use GPy.

**Comment by apaleyes** [comment]
What i meant by "intro code" is exactly what Mark thought: code from "tutorial-intro" notebook.

To add to what Mark suggested about docs and intro level notebooks, I would also consider unit tests to fall into category of things that shouldn't require additional libraries to run.

Integration tests and the rest of notebooks can have other dependencies, i agree.

**Comment by apaleyes** [comment]
Ok, all things considered GPy isn't going away as a dependency any time soon, it seems. Multi-fidelity became an important feature of Emukit that people [use](https://scholar.google.com/scholar?oi=bibs&hl=en&cites=3231735786627322051). GPyOpt, on the other hand, is no longer a dependency. Thus, closing.
