### ISSUE TITLE
Good example of parallel objective evaluation

### ISSUE THREAD

**Issue by apaleyes** [EmuKit/emukit#255]
This issue that surfaced from conversation with @henrymoss .

If you wanted to do parallel evaluations of your objective, you might be able to do that with Emukit, but it isn't obvious how to get started. A good tutorial would be nice to help people out.

**Comment by ekalosak** [comment]
Seems like a producer-consumer architecture with two channels might fit:
- Producer generates batch suggestions and fills a `channel1=queue.Queue()`  with those suggestions
- Producer initializes `channel2=queue.Queue()` for results
- Consumers take `my_suggestion=channel1.pop()` and run the expensive objective on that suggestion
- Consumers return results to `channel2`
- Producer blocks on `new_result=channel2.pop()` until a result is available
- When `new_result` is available, the producer updates the surrogate model, generates a new batch of suggestions `new_suggestions=emukit.get_next_points()`, and replaces the contents of the suggestions channel `with channel1.lock: channel1.clear(); channel1.put(new_suggestions)`
