### ISSUE TITLE
Some code snippets in tutorials are broken

### ISSUE THREAD

**Issue by mmahsereci** [EmuKit/emukit#310]
Note that the [Bayesian Optimization tutorial](https://amzn.github.io/emukit/bayesian-optimization/) still refers to model_free, i.e. the line:

`from emukit.experimental_design.model_free.random_design import RandomDesign`

which leads to the following error when copy/pasting the sample code:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-28-32962e6ab93a> in <module>
----> 1 from emukit.experimental_design.model_free.random_design import RandomDesign
      2 from GPy.models import GPRegression
      3 from emukit.model_wrappers import GPyModelWrapper
      4 
      5 design = RandomDesign(parameter_space) # Collect random points

ModuleNotFoundError: No module named 'emukit.experimental_design.model_free'
```

_Originally posted by @tdiethe in https://github.com/amzn/emukit/issues/219#issuecomment-656271472_

**Comment by apaleyes** [comment]
Fixed!

**Comment by apaleyes** [comment]
Update: new way to import Random is

    from emukit.core.initial_designs import RandomDesign

that's how the linked tutorial now does it too
