### ISSUE TITLE
Abstractmethod decorators for core methods in wrappers

### ISSUE THREAD

**Issue by Croydon-Brixton** [EmuKit/emukit#325]
Hi and thanks for the good work on emukit!
As a minor enhancement, could we add abstractmethod decorators to the wrapper core methods that need to be implemented by users for their custom models? 
This would make it more clear what needs to be implemented from the user's side and what doesn't.

c.f. https://docs.python.org/3/library/abc.html

**Comment by apaleyes** [comment]
Hi! Would you be able to expand that a bit? Which classes are missing this decoractor at the moment? We have them on the range of classes, including base classes for acquisition, stopping condition, etc.

Better yet, just cut us a PR with the changes you'd like to see!

**Comment by apaleyes** [comment]
Suppose this is not an issue anymore
