### ISSUE TITLE
Dynamic LCB

### ISSUE THREAD

**Issue by rvvincelli** [EmuKit/emukit#329]
Hi!

I am looking for a way to bring in the regret-optimized version of the GP-UCB/LCB acquisition as described [here](https://arxiv.org/pdf/0912.3995.pdf) (th.1). I wonder if something like [this](https://gist.github.com/rvvincelli/6e72ab554f03c35e093fdfb1048be34f) is acceptable? The real question is what is the best way to keep track of the iterations, so the `t` variable; in this example we just override the `beta` property at each iteration, as `update_parameters` is the update hook called at the beginning of each iteration.

Please let me know! Thanks,

**Comment by apaleyes** [comment]
We have LoopState object that already tracks iterations. Or if that isn't sufficient you can extend it with whatever additional data you need. E.g. for benchmarking purposes we [add a collection of metrics to it](https://github.com/EmuKit/emukit/blob/master/emukit/benchmarking/loop_benchmarking/benchmarker.py#L65). Would that work?

**Comment by rvvincelli** [comment]
Hi @apaleyes , thanks for answering. Is that object accessible from inside the acquisition class? My point is more to get the information right into the acquisition, rather than getting it from the outside in the optimization loop. I am not sure if I get it, but could you perhaps just illustrate how you would implement the stateful acquisition as above? Thanks,

**Comment by apaleyes** [comment]
oh, good point. we don't have immediate examples of it being used inside the acquisition. I imagine it is technically possible: you would need to implement new Point Calculator that calls your own acquisition and passes state in. Like another 10 lines of code.

Also, at the first glance i don't see anything wrong with your implementation of the Dynamic LCB

**Comment by rvvincelli** [comment]
@apaleyes , thank you for the explanation. If you think it is a good idea I may open a PR, so that we get more feedback anyway. Let me know; thanks again!

**Comment by apaleyes** [comment]
Up to you, really. Emukit will certainly benefit from having Dynamic UCB implementation. But PR in the core lib will require things like code readability and unit tests. If you are happy with that - give it a go for sure. If not, consider adding it into "examples", where requirements aren't as strict.

**Comment by rvvincelli** [comment]
Hi @apaleyes , I'll think about it, thanks! I would say at least a comment, then if I understand how to write proper unit test a PR too. Tx!

**Comment by rvvincelli** [comment]
Opted for an example, see [pr](https://github.com/EmuKit/emukit/pull/332). Thanks!
