### ISSUE TITLE
MUMBO acquisition calculation typo/bug

### ISSUE THREAD

**Issue by NeoChaos12** [EmuKit/emukit#331]
https://github.com/EmuKit/emukit/blob/9f5ba5c1db955621f46faaf6d3913abda1dc4590/emukit/bayesian_optimization/acquisitions/max_value_entropy_search.py#L252-L255

This appears to be incorrectly clipping the variance value when it should instead be clipping the standard deviation. As a direct consequence of this, the proceeding calculations of the acquisition function use the clipped variance instead of the clipped standard deviation, here:

https://github.com/EmuKit/emukit/blob/9f5ba5c1db955621f46faaf6d3913abda1dc4590/emukit/bayesian_optimization/acquisitions/max_value_entropy_search.py#L261

**Comment by apaleyes** [comment]
Casting @henrymoss in here to comment!

**Comment by henrymoss** [comment]
Yeah. That is a mistake!

**Comment by apaleyes** [comment]
Nice, thanks @NeoChaos12 for finding and @henrymoss for confirming. Anyone would like to volunteer themselves to fix?

**Comment by henrymoss** [comment]
Done!
