### ISSUE TITLE
Link to cost sensitive bayes broken

### ISSUE THREAD

**Issue by microprediction** [EmuKit/emukit#334]
https://github.com/EmuKit/emukit/tree/master/emukit/examples/cost_sensitive_bayesian_optimization

**Comment by apaleyes** [comment]
Yup, that link does not work indeed. Can you let us know where did you find it?

**Comment by microprediction** [comment]
Sorry should have added. It is in the list of examples, 
https://github.com/EmuKit/emukit/tree/master/emukit/examples

**Comment by apaleyes** [comment]
Thanks for reporting. Cost sensitivite BO has graduated to the main lib long ago, so I've just removed that entry, and refreshed the overall list
