### ISSUE TITLE
What are the "Optimization restart" and "f" values printed during Bayesian optimisation?

### ISSUE THREAD

**Issue by oulenz** [EmuKit/emukit#335]
When I run Bayesian optimisation, I get the following output on the command line, for each iteration:

`Optimization restart 1/1, f = 749996.4974079899`

Sometimes the numbers for `f` grow very large (like above), while sometimes they are mostly negative, for essentially the same problem (different folds within cross-validation).

My questions are:

* What is `f` here? In the context of optimisation, `f` is generally the function to be optimised, so its use here doesn't make sense. It doesn't seem to be either `x` or `y` either.
* Where does this come from? I can't find the code that produces this within emukit, and a GitHub search seems to point towards an older version of GPy?
* What does `Optimization restart 1/1` mean here?

**Comment by apaleyes** [comment]
This is indeed coming from GPy, or more specifically from the paramz package, on which GPy is built. Here is the reference: https://github.com/sods/paramz/blob/master/paramz/model.py#L118

You start optimization at random initial points, and choose the best solution.  I am not entirely sure what is the huge number, feel free to dig into paramz code if you'd like. 1/1 means that there was only 1 restart requested (that is, no restarts).

If you'd rather not see these, make sure to set `verbose_optimization=false` when creating the GPy wrapper.

**Comment by ekalosak** [comment]
Those `f` values are the log likelihoods achieved in the maximum likelihood estimation for the GP hyperparameters, no?

**Comment by oulenz** [comment]
Ok, thanks! There might be something pathological going on with my data then. It would be nice to learn what the expected pattern is of these log likelihoods (what value they are expected to converge/diverge to).

I'm not sure where I could set `verbose_optimization=false`. [`GPyModelWrapper`](https://github.com/EmuKit/emukit/blob/96299e99c5c406b46baf6f0f0bbea70950566918/emukit/model_wrappers/gpy_model_wrappers.py#L15) doesn't seem to allow that.

PS: I'm following https://emukit.github.io/bayesian-optimization/

**Comment by apaleyes** [comment]
@oulenz my bad, we only defined this parameter for multi-output wrapper. Well, no escape from these prints then! Unless you set `n_restarts=1`, at least this one you certainly can do.

**Comment by oulenz** [comment]
How do you mean set `n_restarts=1`? That's the default value, isn't it?

**Comment by apaleyes** [comment]
it is, just wanted to mention what you can do with the wrapper explicitly.

btw, you are always welcome to inherit this wrapper and overried `optimize` method, silencing GPy that way

**Comment by apaleyes** [comment]
cool, thanks @oulenz and @ekalosak
