### ISSUE TITLE
Complete CI tasks

### ISSUE THREAD

**Issue by apaleyes** [EmuKit/emukit#340]
We have recently migrated to Github Actions #339

A few follow up tasks showed up along the way:
- Enable flake8 linting. It is disabled for some reason, I am guessing to hide embarrassingly many errors 
- Revisit command line tests setup. At the moment we have some weird default stuff going on for executing pytest
- Sort out GPy somehow. It becomes real pain, I wasn't able to install emukit and GPy for any Python versions other than 3.7. Same error as https://github.com/SheffieldML/GPy/issues/874

**Comment by ekalosak** [comment]
Also, https://github.com/SheffieldML/GPy/pull/888 upgrades GPy for 3.9 - 3.8 should have already been working 🤔

**Comment by apaleyes** [comment]
So it does. Added 3.8, thanks @ekalosak for pointing that out

**Comment by apaleyes** [comment]
Seems that all points are taken care of now
