### ISSUE TITLE
cannot import name 'RandomDesign'

### ISSUE THREAD

**Issue by cyxomo** [EmuKit/emukit#341]
I noticed that the issue 'RandomDesign' was still not fixed in version 0.4.7

/`>>> from emukit.experimental_design import RandomDesign
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'RandomDesign'
`
However,in  #310 , I see it has been solved
I was so confused

I installed emukit through pip
`pip install emukit`

**Comment by cyxomo** [comment]
The version 0.4.6 is all right 
if version was updated to 0.4.7 ,'RandomDesign' could not be found

**Comment by apaleyes** [comment]
It is fixed, but in a different way! Random was moved to a different package, please use

    from emukit.core.initial_designs import RandomDesign

I've updated the original issue to clarify that too
