### ISSUE TITLE
GPyModelWrapper.generate_huperparameters_samples changes the value of fixed parameters

### ISSUE THREAD

**Issue by BrunoKM** [EmuKit/emukit#344]
Before starting collecting hyperparameter samples with HMC, the below code adds some random noise to the optimised MAP parameter array.

https://github.com/EmuKit/emukit/blob/f53b6cc7dea6602123f008c0adbb8cb0788ee760/emukit/model_wrappers/gpy_model_wrappers.py#L124-L138

Adding noise in this way, however, alters the value of the parameters which have been fixed with `constrain_fixed()`. For instance:
```
>>> # Specify GPy model with a constrained parameter
>>> kern = GPy.kern.RBF(1)
>>> kern['lengthscale'] = 0.01
>>> kern['lengthscale'].constrain_fixed()
>>> gpy_model = GPy.models.GPRegression(X, Y, kern)
>>> model = GPyModelWrapper(gpy_model)
>>> print(model.model['rbf.lengthscale'])
GP_regression.rbf.lengthscale:
Param([0.01])
>>> samples = model.generate_hyperparameters_samples()
>>> print(model.model['rbf.lengthscale'])
GP_regression.rbf.lengthscale:
Param([0.066441629009533])
```

The correct way to deal with this would be to add noise to the unconstrained parameters only in `generate_hyperparameters_samples()`:
```
# Add noise where parameters aren't fixed
noise = 1. + np.where(self.model._fixes_, np.random.randn(self.model.param_array.size) * 0.01, 0.0)
self.model.param_array[:] = self.model.param_array * noise
```

**Comment by apaleyes** [comment]
Good catch! Not a fan of calling private fields like that, does GPy provide any public method to get the list of fixed params?

Either way, would you like to cut a PR?

**Comment by BrunoKM** [comment]
I think there is some API to get and set unfixed parameters only. And yeah, I'd be happy to send through a small PR
