### ISSUE TITLE
Rename `master` -> `main`

### ISSUE THREAD

**Issue by ekalosak** [EmuKit/emukit#348]
In keeping with community standards for inclusion, I'd suggest we rename the `master` branch to `main`.

**Comment by apaleyes** [comment]
Sure, why not. Let's deal with releasing a new version, and take care of that afterwards

**Comment by ekalosak** [comment]
@apaleyes bump

**Comment by apaleyes** [comment]
Thanks for the bump. This is now done. Here are the commands to run locally

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
