### ISSUE TITLE
import emukit successfully,but others SyntaxError

### ISSUE THREAD

**Issue by AmosJoseph** [EmuKit/emukit#351]
>>> import emukit
>>> from emukit.examples.gp_bayesian_optimization.single_objective_bayesian_optimization import GPBayesianOptimization 
SyntaxError: ('invalid syntax', ('C:\\Users\\Apple1\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\emukit\\examples\\gp_bayesian_optimization\\single_objective_bayesian_optimization.py', 24, 38, '    def __init__(self, variables_list: list, X: np.array, Y: np.array, noiseless: bool = False,\n'))
>>> from emukit.core.loop import UserFunctionResult
File "C:\Users\Apple1\AppData\Local\Programs\Python\Python37\Lib\site-packages\emukit\core\__init__.py", line 4, in <module>
    from .categorical_parameter import CategoricalParameter  # noqa: F401
SyntaxError: ('invalid syntax', ('C:\\Users\\Apple1\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\emukit\\core\\categorical_parameter.py', 14, 28, '    def __init__(self, name: str, encoding: Encoding):\n'))
>>> from emukit.core import ParameterSpace, ContinuousParameter
File "C:\Users\Apple1\AppData\Local\Programs\Python\Python37\Lib\site-packages\emukit\core\__init__.py", line 4, in <module>
    from .categorical_parameter import CategoricalParameter  # noqa: F401
SyntaxError: ('invalid syntax', ('C:\\Users\\Apple1\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\emukit\\core\\categorical_parameter.py', 14, 28, '    def __init__(self, name: str, encoding: Encoding):\n'))

Excuse me, what is wrong,how to handle this problem?
 
Best!

**Comment by apaleyes** [comment]
I am not sure, to be honest. It looks more like something wrong with your Python installation rather than emukit. First thing that comes to mind is type hints, but they were introduced in python 3.5 and you seem to be running 3.7.

Can you get a clean python installation and try again?

**Comment by apaleyes** [comment]
Closing this, as it's clearly not Emukit (all our builds pass, and syntax error like that would fail them instantly).
