### ISSUE TITLE
Stale imports in DOE tutorial

### ISSUE THREAD

**Issue by charelstoncrabb** [EmuKit/emukit#352]
It looks like a couple of the imports in the [experimental design tutorial](https://emukit.github.io/experimental-design/) are stale:

```
>>> from emukit.experimental_design.model_free.latin_design import LatinDesign
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'emukit.experimental_design.model_free'
```

Not a big deal but had to do a grep to find where the `LatinDesign` was:
`core/initial_designs/latin_design.py:15:class LatinDesign(ModelFreeDesignBase):`

**Comment by apaleyes** [comment]
Ah, thanks for pointing out. model_base/model_free dichotomy in packages is indeed no more. Fixed!
