### ISSUE TITLE
automatic relevance determination(ARD)

### ISSUE THREAD

**Issue by AmosJoseph** [EmuKit/emukit#354]
Excuse me,ARD = True or False?
When True and when False？
I wonder how to set it.

Best!

**Comment by apaleyes** [comment]
It allows you to control the treament of dimensions, if you think they are all equally relevant or what to learn their relative importance. Better refer to GPy for details, e.g.: https://github.com/SheffieldML/GPy/blob/devel/GPy/kern/src/stationary.py

**Comment by AmosJoseph** [comment]
OK.Thank you！
