### ISSUE TITLE
problem concerning convergence

### ISSUE THREAD

**Issue by AmosJoseph** [EmuKit/emukit#356]
Hi!

I try expotential and Matern 5/2 kernal for 10 variables,but do not converge or with a trend to converge after 40 iterations.
Could you give any suggestion?

How about building (sparse) GP with evaluated samples to run iteration for BO?
Will this converge?

Thank you!

Best!

**Comment by apaleyes** [comment]
That is very highly dependent on the problem. Such behavior can be happening for a ton of reasons. Maybe the objective is all bumpy, with many local minima, maybe there is no structure in the parameter space, maybe the objective is noisy. I am afraid I don't have any generic advice to give here.

**Comment by AmosJoseph** [comment]
What do you mean by "maybe there is no structure in the parameter space"?

**Comment by apaleyes** [comment]
That's more about the cases when you have many categorical variables. There are techniques that could be used in such cases: http://proceedings.mlr.press/v80/lu18c.html . But if the space is unstructured, you optimization essentially becomes brute force no matter what you do
