### ISSUE TITLE
normalize X or Y?

### ISSUE THREAD

**Issue by AmosJoseph** [EmuKit/emukit#362]
Hi!

When GP is built,normalizing X will make the GP more robust.

But why normalizing Y is done in the code?

Best!

**Comment by apaleyes** [comment]
Just for clarity, which code are you referring to?

**Comment by AmosJoseph** [comment]
This one:
def normalize_Y(Y, indexD):
--
50 | max_idx = np.max(indexD)
51 | Y_mean = np.zeros(max_idx + 1)
52 | Y_std = np.zeros(max_idx + 1)
… |  
90 | num_steps = 100 * n_samples + 1
91 | lr = 1e-2
92 | batch_size = 5
93 |  
94 | # load and normalize data
95 | if args.benchmark == "forrester":


Below X,Y are both normalized:
# Select objective, we demonstrate here with the 4 dimensional Sushi data
--
14 | objective = evalset.test_funcs.Sushi()
15 |  
16 | # Normalize the objective and add noise:
17 | objective.init_normalize_X() # scale bounds between 0 and 1
18 | objective.init_normalize_Y() # scale function maximum and minimum between 0 and 1

What is the difference between the two cases above？

**Comment by apaleyes** [comment]
Both these codes are from examples, which I am not closely familiar with. Generally Y is normalized so that optimization of the acquisition function is easier. I suspect that's the reasoning behind normalizing Y in both of these examples.
