### ISSUE TITLE
IntegratedHyperParameterAcquisition.update_parameters() uses different settings to generate samples than at initialisation

### ISSUE THREAD

**Issue by BrunoKM** [EmuKit/emukit#363]
Compare the samples generated with `update_parameters()`
https://github.com/EmuKit/emukit/blob/b7939897ebcff2281d0bb017186fd4ecf059df93/emukit/core/acquisition/integrated_acquisition.py#L70-L71
to those generated at initialisation:
https://github.com/EmuKit/emukit/blob/b7939897ebcff2281d0bb017186fd4ecf059df93/emukit/core/acquisition/integrated_acquisition.py#L27-L28
Different settings for HMC sampling will be used in the two cases – `update_parameters()` ignores the HMC settings specified by the user at initialization.

**Comment by apaleyes** [comment]
@henrymoss these additional parameters came from here: https://github.com/EmuKit/emukit/pull/241 . Do you happen to remember if there was a good reason not to use them in the `update`? If we both simply missed it, no bother, it's a simple fix, but just want to check first.

**Comment by henrymoss** [comment]
I think I just missed it! The settings should be carried

**Comment by apaleyes** [comment]
thanks both, this is fixed now
