### ISSUE TITLE
Incongruence in Constraint Definitions?

### ISSUE THREAD

**Issue by ntenenz** [EmuKit/emukit#371]
Unless I'm missing something, there may be a bit of disagreement between the documentation and code in how the endpoints of constraints are treated. The documentation seems to indicate that the ranges are open, whereas the code indicates they're closed.

For example,
* `LinearInequalityConstraint`
  * *Docstring:* ["(n_constraint, n_x_dims) matrix in b_lower < Ax < b_upper"](https://github.com/EmuKit/emukit/blob/f9e7173d2604f781da34f8d26fd210dc0e895697/emukit/core/constraints.py#L53)
  * *Code:* [`np.all((ax >= self.lower_bound) & (ax <= self.upper_bound), axis=1)`](https://github.com/EmuKit/emukit/blob/f9e7173d2604f781da34f8d26fd210dc0e895697/emukit/core/constraints.py#L79)
* `NonlinearInequalityConstraint` 
  * *Docstring:* ["function defining constraint in b_lower < fun(x) < b_upper."](https://github.com/EmuKit/emukit/blob/f9e7173d2604f781da34f8d26fd210dc0e895697/emukit/core/constraints.py#L89)
  * *Code:* [`np.all([fun_x >= self.lower_bound, fun_x <= self.upper_bound], axis=0)`](https://github.com/EmuKit/emukit/blob/f9e7173d2604f781da34f8d26fd210dc0e895697/emukit/core/constraints.py#L111)

Am I missing something obvious here?

**Comment by apaleyes** [comment]
It appears to me that you are correct, and it is just a miss on our part. Would you like to fix it with a PR, or prefer us to do it?

**Comment by ntenenz** [comment]
Happy to submit a PR, but could you clarify which is the preferred behavior, open vs closed?

**Comment by apaleyes** [comment]
Closed please, `<= ... <=`. Thanks!
