### ISSUE TITLE
How to speed up the training and prediction with GPU like GPyTorch and GPFlow?

### ISSUE THREAD

**Issue by intellisense-team** [EmuKit/emukit#376]
HI,

I just want to know how to speed up the training and prediction with GPU like GPyTorch and GPFlow? Since the amount of the data is huge like 100,000 points. I really want to realize the multi-fidelity models with GPU support.

Can someone give me some advices?

**Comment by apaleyes** [comment]
Hi there! Have a look at the multi-fidelity deep GP example implemented in Emukit: https://github.com/EmuKit/emukit/tree/main/emukit/examples/multi_fidelity_dgp

It is built with GPFlow 1.x and provides an Emukit-compatible model.
