### ISSUE TITLE
Uncertainty sampling weigths in BQ are missing a square

### ISSUE THREAD

**Issue by mmahsereci** [EmuKit/emukit#377]
The variances for uncertainty sampling in BQ are usually multiplied with the density of the integration measure *squared*. Currently they are only multiplied with the density (without the square) , see [here](https://github.com/EmuKit/emukit/blob/main/emukit/quadrature/acquisitions/uncertainty_sampling.py#L43). 

The default should be with the square, and optionally without it, but the change might break someones code. Not sure how many people use the BQ uncertainty sampling acquisition function though. 

Options:
1. change the default to square, and optionally non-square (is better but might break someones code)
2. leave default at non-square, and optionally square (not the common default, does not break code)

I would still opt for 1. I think. Thoughts @apaleyes, @alpiges ?

**Comment by apaleyes** [comment]
I think that's fine, because you won't break anybody's code that uses specific versions of Emukit. Since the interface won't change, i don't see any problem with option 1

**Comment by alpiges** [comment]
I agree with @apaleyes that switching to the square does not cause any harm.
