### ISSUE TITLE
Example when the function is not available

### ISSUE THREAD

**Issue by Atulsingh92** [EmuKit/emukit#389]
Hello, 

This [link](https://www.blopig.com/blog/wp-content/uploads/2019/10/GPyOpt-Tutorial1.html) , in its 2d example has a function in x and y. 
Is this a necessasity, or can the BayesianOptimization(f=obj_func, domain=domain), be defined with just the output array instead, incase, one does not have the function available?

If so, how could I do so?

I assumed passing a GPy.model.GPRegression( 2dimensional x, 1dimensional y, kernel) to the obj_func above should suffice, but instead it is a ""GPRegression" object is not callable" error.

**Comment by apaleyes** [comment]
Hello! To begin with, the link you gave talks about GPyOpt. Is that what you are using? Unfortunately GPyOpt was discontinued some time ago, and this repo would be a wrong place to seek support for it.

If it is Emukit you are after, there is an example of how to use Emukit in case you don't have access to objective: [External objective function evaluation in Bayesian optimization with Emukit](https://nbviewer.org/github/emukit/emukit/blob/main/notebooks/Emukit-tutorial-bayesian-optimization-external-objective-evaluation.ipynb)

**Comment by Atulsingh92** [comment]
Does, passing a m = GPy.model.GPRegression(X,Y,k) to Y_new makes sense?
The idea is if I cannot call the original objective function, i could pass its surrogate (m) instead.
