### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mmahsereci** [EmuKit/emukit#426]
@apaleyes what do you think about a new release on pypi? The `quadrature` package changed quite a bit in the last months.

**Comment by apaleyes** [comment]
Great, good spot! My other task is done too, and resulted in no changes in Emukit.

Shall we get to the bottom of #421 before releasing though?

**Comment by mmahsereci** [comment]
> Shall we get to the bottom of #421 before releasing though?

yes, sounds good.

**Comment by mmahsereci** [comment]
I was away during the summer for a bit. Found one more kernel embedding as well #430 . That should now be fairly complete for `quad` though (famous last words).

**Comment by mmahsereci** [comment]
Are we ready now for new release @apaleyes ?
