### ISSUE TITLE
Obtaining difference values between fidelities

### ISSUE THREAD

**Issue by Atulsingh92** [EmuKit/emukit#436]
Hello, 
I wanted to know if there is a way to obtain this d_s(x) or the difference model for the equation shown [here](https://github.com/EmuKit/emukit/blob/main/emukit/multi_fidelity/kernels/linear_multi_fidelity_kernel.py).
The scaling parameter I am aware is available from one of the values within `lin_mf_model.gpy_model.param_array` command, however can't seem to find the difference values. (This is seen in [code](https://uk.mathworks.com/academia/books/engineering-design-via-surrogate-modelling-forrester.html) from Forrester's book in Matlab.) 
How can I get this d_s(x) values within emukit?

**Comment by apaleyes** [comment]
Answered with no further feedback for two years, closing. Please reach out again if necessary!
