### ISSUE TITLE
Nonlinear Multi-Fidelity Problem

### ISSUE THREAD

**Issue by pzhcdh** [EmuKit/emukit#445]
In https://github.com/EmuKit/emukit/blob/main/notebooks/Emukit-tutorial-multi-fidelity.ipynb, it is only mentioned that linear problems are only modeled using high-precision data. How can nonlinear problems be modeled using only high-precision data? It would be great if I could get a reply.

**Comment by apaleyes** [comment]
Hi! Can you clarify which section of the notebook you are referring to? There is nothing inherently special about linear/non-linear in that respect. In both cases it is expected that high  fidelity data is of better quality.

**Comment by pzhcdh** [comment]
In the linear problem, there are results of using only high-precision data for GPR for comparison, but for nonlinear problems, there is no result of using only high-precision data for GPR. I would like to ask how to use only high-precision data for GPR in nonlinear cases, so that it can be seen that the low-precision data has improved the results.
