### ISSUE TITLE
about GPR and kriging method

### ISSUE THREAD

**Issue by silencetraveler** [EmuKit/emukit#449]
Hello, the author. I don't quite understand the difference between GPR and kriging method, or the difference between multi-fidelity GPR and co-kriging. They are all regression methods based on Gaussian process, and both use the correlation between Covariance function and data for modeling and prediction. Some documents say that it is the same method, and some documents say that it is not the same. I would like to know some of your insights on this matter. Thank you for your reply.

**Comment by apaleyes** [comment]
Hello! I am by no way an expert in the matter, so cannot offer insights, only my own opinions. To me, kriging and GP regression are two ways to refer to exact same method, and the difference is that some fields (geostatistics) use one, while others (statistical emulation) another. I am afraid this is no different from [many](https://stats.stackexchange.com/questions/48405/confusion-related-to-difference-of-kriging-and-gaussian-processes) [other](https://arxiv.org/pdf/2207.10138.pdf) [sources](https://en.wikipedia.org/wiki/Kriging) found around the web though.

**Comment by apaleyes** [comment]
Hopefully the question is answered, closing
