### ISSUE TITLE
Typo in emukit\test_functions\multi_fidelity\currin.py

### ISSUE THREAD

**Issue by jeannotalpin** [EmuKit/emukit#450]
Hello, 
On emukit version 0.4.10, there is a typo in Currin test function located here: `emukit\test_functions\multi_fidelity\currin.py`

Lines 35 to 39 read:
```python
return (
            1
            - np.exp(-0.5 / x2)
            * ((2300 * x1**3 + 1900 * x1**2 + 2092 * x1 + 60) / (100 * x1**3 + 500 * x1**2 + 4 * x1 + 20))
        )[:, None]
```

But should be:
```python
return (
            (1
            - np.exp(-0.5 / x2))
            * ((2300 * x1**3 + 1900 * x1**2 + 2092 * x1 + 60) / (100 * x1**3 + 500 * x1**2 + 4 * x1 + 20))
        )[:, None]
```
According to https://www.sfu.ca/~ssurjano/curretal88exp.html: missing parenthesis around the first factor.

Thanks.

**Comment by apaleyes** [comment]
Hi @jeannotalpin . Thank you for the report, checking the page it appears that the typo is indeed there, great catch!

Would you like to contribute a small PR for this, or prefer us to just fix it?

**Comment by apaleyes** [comment]
Thanks for taking care of this!
