### ISSUE TITLE
ImportError: cannot import name 'Tester' from 'numpy.testing'

### ISSUE THREAD

**Issue by fteich** [EmuKit/emukit#455]
Hi,

when i am trying to run the following line of code:

"from emukit.multi_fidelity.convert_lists_to_array import convert_xy_lists_to_arrays"

i get the following error:

"ImportError: cannot import name 'Tester' from 'numpy.testing' (C:\Users\User\pythonProjects\lib\site-packages\numpy\testing\__init__.py)"

I am using python 3.9 (Anaconda) and numpy 1.23.5. Can anyone help?

Cheers,
Fabian

**Comment by apaleyes** [comment]
Just tried exact same setup (python 3.9, numpy 1.23.5) and it worked fine. I suspect some sort of a python path issue. Try creating a new clean virtualenv, install emukit with all dependencies and see if the issue goes away

**Comment by apaleyes** [comment]
Make sure your numpy is actually <1.25, as there are reports of similar bugs in GPy recently: https://github.com/SheffieldML/GPy/issues/1004#issuecomment-1749487425

**Comment by fteich** [comment]
Thanks a lot for your help! Creating a clean virtualenv was the way to go. If further errors occur i will try to downgrade numpy.
