### ISSUE TITLE
Question on the tutorial of multi-fidelity modeling

### ISSUE THREAD

**Issue by stdrj** [EmuKit/emukit#466]
Hi together,

I'm running the [tutorial of multi-fidelity model of emukit.](https://nbviewer.org/github/emukit/emukit/blob/main/notebooks/Emukit-tutorial-multi-fidelity.ipynb) And I noticed some strange behaviors regarding the uncertainty. I wonder whether someone can help.

I'm referring to the linear multi-fidelity model. In the tutorial, **12 low-f data and 6 high-f data** are used. Then we have observed this nice figure with reasonable confidence interval of the high fidelity prediction.
![12low-6high](https://github.com/user-attachments/assets/4db4a92d-2cfd-4770-bfe3-e90d5b22613e)

It becomes a little bit wierd when I try to use **50 low-f data and 2 high-f data**. Then I observed the following figure:
![50low-2high](https://github.com/user-attachments/assets/10ef8fb8-97db-4e74-a998-d9e73ad779b3)
To my understanding, due to the extreme low number of high fidelity data, the model should give a very big confidence interval. But in this figure the prediction of the high fidelity model is clearly over-confident. (Both the high and low fidelity data have been defined to be noiseless.)

Since I'm going to optimize the low fidelity and high fidelity function in two phases separately (unlike in the standard multi-fidelity case, where the next experiment can be either low or high fidelity evaluation), there will be a lot of low fidelity data and only a few high fidelity data in the beginning of the second phase of the optimization in my case. An incorrect uncertainty quantification is affecting the acquisition function (expected improvement) to explore the correct place of the high fidelity function. So I'd like to know whether I have some misunderstandings, or this just happens due to the unnormal propertion of high-f and low-f data.

Thanks a lot!

**Comment by apaleyes** [comment]
Hi @stdrj! Would you be able to share the code that you used to plot this second figure? Also, I do not see any confidence intervals on the second figure at all, but I am assuming the "overconfidence" you are referring to is due to what happens to the high fidelity prediction after `x>0.5`, right?

**Comment by stdrj** [comment]
Thanks for the reply! Yes I admit adding more HF evaluation points will help the model go to the right direction. Regarding the following suggestion: 

> I recommend playing with the LF/HF ratio to get a better sense of what's going on

Since I'm actually doing 2-stage optimization, namely by the time for HF experiments no LF evaluations can be done anymore, at the beginning of the HF experiments there will be a lot of LF data and only very few HF data (from initialization). Do you suggest to initialize more HF data and then let the acquisition function decide? Can too many LF data points harm the HF execution phase? (I really hadn't realize too much LF data can harm the "transfer learning")

Thanks a lot!

**Comment by apaleyes** [comment]
Yes, it appears that in your case you need a bit more initial HF points.

There might be more advanced thing you could do in this setup that are currently not implemented in Emukit. We had this issue open for a while, but never got around to work on it. At least it has some references that might be interesting for you to look at: https://github.com/EmuKit/emukit/issues/256

**Comment by stdrj** [comment]
Thank you for the information! It really helps a lot.
