### ISSUE TITLE
How to use the optimizer for a custom model and custom acquisition function

### ISSUE THREAD

**Issue by stdrj** [EmuKit/emukit#467]
Hello together,

I'm using emukit to construct a custom model and acquisition function for bayesian optimization. I wonder how I can **use the existing optimizer in a right way to optimize the acquisition function** and generate the next data to evaluate. My wish is to use the L-BFGS with multiple random starting points. Here's my code snippet:
```
from emukit.bayesian_optimization.acquisitions.expected_improvement import MeanPluginExpectedImprovement    
def acquisition_next_x(X_plot_h_in, lin_mf_model_in, param_space): 

    nei_acquisition = MeanPluginExpectedImprovement_multifidelity(lin_mf_model_in.gpy_model)

    # Set up the optimizer with the correct parameter space
    optimizer = GradientAcquisitionOptimizer(param_space, num_anchor=50)

    # Optimize the acquisition function
    x_new_out = optimizer.optimize(nei_acquisition)
    improvement = nei_acquisition.evaluate(X_plot_h_in)
    return np.array(x_new_out[:-1]).squeeze(0), improvement
```
Currently this compiles, but I saw that x_new_out doesn't correspond to maximum of improvement. Am I using the optimizer incorrectly?It's a little bit tricky to generate a code set as a minimal reproducible example in my case so I'll just put the snippet here for now. Thanks a lot!

**Comment by apaleyes** [comment]
Hi! It looks fine at the first glance. Can you elaborate on how did you arrive at this conclusion?
> x_new_out doesn't correspond to maximum of improvement

**Comment by stdrj** [comment]
Hi @apaleyes ! Thanks for the reply. I noticed this simply because I plotted the variable "improvement" on a dense grid, and saw that the x_new_out doesn't point to a maximum. Below is the figure of "improvement" vs "X_plot_h_in" in one iteration, where x_new_out = (array([[5.52317686]]), array([[nan]])), although I'm not sure where does the second output nan comes from...

![image](https://github.com/user-attachments/assets/b74163f0-a84e-48f3-b366-cb4d654dc435)

**Comment by stdrj** [comment]
Oh I just read the source code for optimizer.optimize(). It seems that the function returns a tuple (x_opt, improvement_max). In my case, x_new_out = (array([[5.52317686]]), array([[nan]])), which means that actually the definition of acquisition function is not valid. Actually I defined a custon acquisition function by inheriting from MeanPluginExpectedImprovement: 

```
class MeanPluginExpectedImprovement_multifidelity(MeanPluginExpectedImprovement):
    def __init__(self, model, jitter: float = 0.0) -> None:
        """
        A variant of expected improvement that accounts for observation noise.
        """
        super().__init__(model=model, jitter=jitter)

    def _get_y_minimum(self) -> np.ndarray:
        """Return the smallest model mean prediction at the previously observed points."""
        means_at_prev, _ = self.model.predict_noiseless(self.model.X[self.model.X[:,-1]==1])
        return np.min(means_at_prev, axis=0)

    def _get_model_predictions(self, x) -> Tuple[np.ndarray, np.ndarray]:
        """Return the likelihood-free (i.e. without observation noise) prediction from the model."""
        return self.model.predict_noiseless(x)
```
In my case, the model is a linear multi-fidelity model, where unlike standard models there are two GPs under the hood and X has  also an additional column of fidelity values. So my assumptions are the gradient calculation is not properly executed
